apiVersion: v1
kind: Pod
metadata:
  name: redis-new
  labels:
    run: redis
    tier: backend
    type: apps
  namespace: default
spec:
  
  containers:
  - name: redis
    image: redis:latest
    ports:
    - containerPort: 6379 
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: disktype
            operator: In
            values:
            - hdd