apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ds
  labels:
    app: nginx
    type: frontend
    env: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      type: frontend
      env: demo
  template:
    metadata:
      labels:
        app: nginx
        type: frontend
        env: demo
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
    