apiVersion: v1
kind: Servicd
metadata:
  name: nginx-lb
  labels:
    app: nginx
    type: frontend
    env: demo
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
        app: nginx
        type: frontend
        env: demo
