apiVersion: v1
kind: Pod
metadata:
  name: multicontainerpod
  labels: 
    env: demo
    name: myapp-demo
spec:
  containers:
  - name: myapp-container
    image: busybox:1.28
    env:
    - name: FRISTNAME
      value: "Prakash"
    command: ['sh', '-c', "echo The app is running; sleep 3600"]
  initContainers:
  - name: init-container
    image: busybox:1.28
    command: ['sh', '-c']
    args: ['until nslookup myservice.default.svc.cluster.local; do echo waiting for myservice; sleep 2; done;']

