apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  labels:
    app: nginx
    type: frontend
    env: demo
spec:
  replicas: 3
  selector:
    app: nginx
    type: frontend
    env: demo
  template:
    metadata:
      labels:
        app: nginx
        type: frontend
        env: demo
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80